server:
  port: 8888

spring:
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/gekal-study-spring/config-server-sample.git
          searchPaths: config-sample
          # username: trolley
          # password: strongpassword
